name: ziberlive
description: A roommate collaboration app for shared living management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # P2P Networking
  nearby_connections: ^3.0.1
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.1.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Ads
  google_mobile_ads: ^4.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Charts for visualizations
  fl_chart: ^0.65.0
  
  # Encryption
  encrypt: ^5.0.1
  crypto: ^3.0.3
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  
  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: ZiberFont
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700